name: Default CI
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make build directory
        run: mkdir build/
      - name: Generate build files
        run: cd build && cmake ..
      - name: Compile binaries
        run: cd build && cmake --build .
      - name: Run the test binary
        run: build/test/Test
      